name: 'S3 deployment'
description: 'Deploys assets to S3 bucket'
inputs:
  bucket:
    description: 'Destination bucket'
    required: true
  source-dir:
    description: 'Dist directory'
    required: true
  max-days:
    description: 'Maximum number of days to keep an asset after it became unused'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'