name: 'S3 deployment'
description: 'Deploys assets to S3 bucket'
inputs:
  secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  access-key-id:
    description: 'AWS Key ID'
    required: true
  bucket:
    description: 'Destination bucket'
    required: true
  region:
    description: 'AWS region'
    required: true
  source-dir:
    description: 'Dist directory'
    required: true
  max-days:
    description: 'Maximum number of days to keep an asset after it became unused'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'